plugins:
  - jekyll-feed
  - jekyll-sitemap

# SEO Stuff
author: Will Smith
description: Srsly, you guys...
lang: en
locale: en_GB
url: "https://thewismit.com"
baseurl: ""

# RSS feeds
feed:
  posts_limit: 20
