plugins:
  - jekyll-feed
  - jekyll-sitemap

# SEO Stuff
author: Will Smith
description: Srsly, u guys...
lang: en
locale: en_GB
timezone: America/New_York
url: "https://thewismit.com"
baseurl: ""

# RSS feeds
feed:
  posts_limit: 20
